namespace KSword.Sandbox.Abstractions.Guest;

/// <summary>
/// Lists files and guest paths staged before sample execution.
/// Inputs are generated by host planning, processing carries path contracts
/// only, and the record is returned to runbook and guest staging layers.
/// </summary>
public sealed record GuestPayloadManifest
{
    public Guid JobId { get; init; }

    public string SampleGuestPath { get; init; } = string.Empty;

    public string AgentGuestPath { get; init; } = string.Empty;

    public string? R0CollectorGuestPath { get; init; }

    public List<string> AdditionalGuestFiles { get; init; } = [];
}
