using KSword.Sandbox.Abstractions;

namespace KSword.Sandbox.Agent.Collection;

/// <summary>
/// Normalizes guest-agent self-noise and collection-noise metadata without
/// changing sample behavior event semantics.
/// </summary>
internal static class GuestSelfNoiseMetadata
{
    /// <summary>
    /// Applies self-noise tags to known guest supervision, diagnostic, and
    /// optional artifact collection events.
    /// </summary>
    public static void Apply(IEnumerable<SandboxEvent> events)
    {
        foreach (var evt in events)
        {
            Apply(evt);
        }
    }

    /// <summary>
    /// Applies self-noise tags to one event when its event type is known to be
    /// generated by the agent or by an optional evidence collection lane.
    /// </summary>
    public static void Apply(SandboxEvent evt)
    {
        GuestArtifactEventQuality.Apply(evt);

        if (!ShouldTagAsSelfNoise(evt))
        {
            return;
        }

        ApplySelfNoiseBehaviorFlags(evt.Data);
        AddIfMissing(evt.Data, "sampleBehaviorCandidateReason", "guest-agent-collection-or-diagnostic-self-noise");

        if (IsDiagnosticOrCollectionHealth(evt))
        {
            AddIfMissing(evt.Data, "collectionHealth", "true");
        }

        AddIfMissing(evt.Data, "zhMessage", ZhMessage(evt.EventType));
        AddIfMissing(evt.Data, "zhHint", ZhHint(evt.EventType));
    }

    private static bool ShouldTagAsSelfNoise(SandboxEvent evt)
    {
        var eventType = evt.EventType ?? string.Empty;
        if (StartsWithAny(
            eventType,
            "agent.",
            "probe.",
            "r0collector.",
            "screenshot.",
            "memory_dump.",
            "packet_capture.",
            "artifact.manifest."))
        {
            return true;
        }

        if (string.Equals(eventType, "environment.snapshot", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(eventType, "analysis.wait_remaining", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (EndsWithAny(
            eventType,
            ".capture_failed",
            ".capture_skipped",
            ".capture_truncated",
            ".read_failed",
            ".parse_failed",
            ".write_failed"))
        {
            return true;
        }

        return DataEquals(evt, "collectionHealth", "true") ||
            DataEquals(evt, "artifactDiagnosticEvent", "true") ||
            DataEquals(evt, "summaryEvent", "true") ||
            DataEquals(evt, "behaviorCounted", "false") ||
            DataEquals(evt, "nonbehavior", "true");
    }

    private static bool IsDiagnosticOrCollectionHealth(SandboxEvent evt)
    {
        var eventType = evt.EventType ?? string.Empty;
        return DataEquals(evt, "collectionHealth", "true") ||
            DataEquals(evt, "artifactDiagnosticEvent", "true") ||
            DataEquals(evt, "summaryEvent", "true") ||
            eventType.Contains("skipped", StringComparison.OrdinalIgnoreCase) ||
            eventType.Contains("failed", StringComparison.OrdinalIgnoreCase) ||
            eventType.Contains("timeout", StringComparison.OrdinalIgnoreCase) ||
            eventType.Contains("summary", StringComparison.OrdinalIgnoreCase) ||
            eventType.StartsWith("probe.", StringComparison.OrdinalIgnoreCase) ||
            eventType.StartsWith("r0collector.", StringComparison.OrdinalIgnoreCase);
    }

    private static string ZhMessage(string? eventType)
    {
        if (eventType is not null)
        {
            if (eventType.StartsWith("r0collector.", StringComparison.OrdinalIgnoreCase))
            {
                return "R0Collector sidecar 监督事件由 Guest Agent 产生，用于说明驱动采集链路状态。";
            }

            if (eventType.StartsWith("screenshot.", StringComparison.OrdinalIgnoreCase))
            {
                return "截图采集事件由 Guest Agent 产生，用于说明截图证据的采集状态。";
            }

            if (eventType.StartsWith("memory_dump.", StringComparison.OrdinalIgnoreCase))
            {
                return "内存转储采集事件由 Guest Agent 产生，用于说明 dump 证据的采集状态。";
            }

            if (eventType.StartsWith("packet_capture.", StringComparison.OrdinalIgnoreCase))
            {
                return "网络抓包采集事件由 Guest Agent 产生，用于说明 PCAP/PCAPNG 证据的采集状态。";
            }
        }

        return "Guest Agent 自身或采集通道诊断事件已记录。";
    }

    private static string ZhHint(string? eventType)
    {
        if (eventType is not null && eventType.StartsWith("r0collector.", StringComparison.OrdinalIgnoreCase))
        {
            return "该事件不代表样本行为；请结合 driver-events JSONL、stdout/stderr 日志和 manifest 完整性字段判断 R0 证据覆盖情况。";
        }

        if (eventType is not null &&
            (eventType.StartsWith("screenshot.", StringComparison.OrdinalIgnoreCase) ||
             eventType.StartsWith("memory_dump.", StringComparison.OrdinalIgnoreCase) ||
             eventType.StartsWith("packet_capture.", StringComparison.OrdinalIgnoreCase)))
        {
            return "该事件不代表样本行为；请结合 captureState/status、reason、artifactRelativePath、sizeBytes 和 sha256 判断证据是否可用。";
        }

        return "该事件用于解释 Guest Agent 自身、采集健康或证据链状态，不应计入样本行为统计。";
    }

    private static bool StartsWithAny(string value, params string[] prefixes)
    {
        return prefixes.Any(prefix => value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase));
    }

    private static bool EndsWithAny(string value, params string[] suffixes)
    {
        return suffixes.Any(suffix => value.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));
    }

    private static bool DataEquals(SandboxEvent evt, string key, string expected)
    {
        return evt.Data.TryGetValue(key, out var value) &&
            string.Equals(value, expected, StringComparison.OrdinalIgnoreCase);
    }

    private static void ApplySelfNoiseBehaviorFlags(IDictionary<string, string> data)
    {
        data["behaviorCounted"] = "false";
        data["nonbehavior"] = "true";
        data["notSampleBehavior"] = "true";
        data["sampleBehaviorCandidate"] = "false";
    }

    private static void AddIfMissing(IDictionary<string, string> data, string key, string value)
    {
        if (!data.TryGetValue(key, out var existing) || string.IsNullOrWhiteSpace(existing))
        {
            data[key] = value;
        }
    }
}
