using System.Text.Json;
using KSword.Sandbox.Abstractions;

namespace KSword.Sandbox.Agent.Output;

/// <summary>
/// Reads driver JSON Lines generated by the R0 collector sidecar.
/// Inputs are JSONL paths; processing deserializes each line independently;
/// methods return normalized driver events or parse-error events.
/// </summary>
internal sealed class DriverJsonLinesReader
{
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    /// <summary>
    /// Reads all driver events from a JSONL file when present.
    /// The input is an optional path, processing tolerates missing files, and
    /// the method returns parsed events.
    /// </summary>
    public IReadOnlyList<SandboxEvent> Read(string? path)
    {
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
        {
            return [];
        }

        var events = new List<SandboxEvent>();
        foreach (var line in File.ReadLines(path))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            try
            {
                var evt = JsonSerializer.Deserialize<SandboxEvent>(line, JsonOptions);
                if (evt is not null)
                {
                    events.Add(evt with { Source = string.IsNullOrWhiteSpace(evt.Source) ? "driver" : evt.Source });
                }
            }
            catch (JsonException)
            {
                events.Add(new SandboxEvent { EventType = "driver.parse_error", Source = "guest", Path = path, Data = { ["line"] = line } });
            }
        }

        return events;
    }
}
