using System.Text.Json;
using KSword.Sandbox.Abstractions;

namespace KSword.Sandbox.Agent.Output;

/// <summary>
/// Reads driver JSON Lines generated by the R0 collector sidecar.
/// Inputs are JSONL paths; processing deserializes each line independently;
/// methods return normalized driver events or parse-error events.
/// </summary>
internal sealed class DriverJsonLinesReader
{
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    /// <summary>
    /// Reads all driver events from a JSONL file when present.
    /// The input is an optional path, processing tolerates missing files, and
    /// the method returns parsed events.
    /// </summary>
    public IReadOnlyList<SandboxEvent> Read(string? path)
    {
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
        {
            return [];
        }

        var events = new List<SandboxEvent>();
        try
        {
            foreach (var line in ReadSharedLines(path))
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                try
                {
                    using var document = JsonDocument.Parse(line);
                    var hasSource = document.RootElement.ValueKind == JsonValueKind.Object &&
                        document.RootElement.EnumerateObject().Any(property =>
                            string.Equals(property.Name, "source", StringComparison.OrdinalIgnoreCase));
                    var evt = JsonSerializer.Deserialize<SandboxEvent>(line, JsonOptions);
                    if (evt is not null)
                    {
                        events.Add(evt with { Source = !hasSource || string.IsNullOrWhiteSpace(evt.Source) ? "driver" : evt.Source });
                    }
                }
                catch (JsonException)
                {
                    events.Add(new SandboxEvent { EventType = "driver.parse_error", Source = "guest", Path = path, Data = { ["line"] = line } });
                }
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            events.Add(new SandboxEvent
            {
                EventType = "driver.read_error",
                Source = "guest",
                Path = path,
                Data =
                {
                    ["exceptionType"] = ex.GetType().FullName ?? ex.GetType().Name,
                    ["message"] = ex.Message
                }
            });
        }

        return events;
    }

    /// <summary>
    /// Reads JSONL rows using permissive file sharing so the guest agent can
    /// import rows immediately after sidecar shutdown while the filesystem is
    /// still settling.
    /// </summary>
    private static IEnumerable<string> ReadSharedLines(string path)
    {
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
        using var reader = new StreamReader(stream);
        while (reader.ReadLine() is { } line)
        {
            yield return line;
        }
    }
}
