namespace KSword.Sandbox.Web.Contracts;

/// <summary>
/// Inputs: success state, optional data, optional error, and the response generation timestamp.
/// Processing: standardizes successful and failed endpoint payload shapes for future endpoint modules.
/// Return behavior: instances are serialized directly by ASP.NET Core result helpers.
/// </summary>
/// <typeparam name="T">Payload type returned by the endpoint when the operation succeeds.</typeparam>
/// <param name="Succeeded">Indicates whether the endpoint operation completed successfully.</param>
/// <param name="Data">Optional payload generated by the endpoint.</param>
/// <param name="Error">Optional error generated by validation or exception mapping code.</param>
/// <param name="GeneratedAtUtc">UTC timestamp captured when the payload was created.</param>
public sealed record ApiEnvelopeContract<T>(
    bool Succeeded,
    T? Data,
    ApiErrorContract? Error,
    DateTimeOffset GeneratedAtUtc)
{
    /// <summary>
    /// Inputs: a successful payload and a UTC timestamp from the caller.
    /// Processing: wraps the payload with a successful envelope and clears the error field.
    /// Return behavior: returns an envelope suitable for Results.Ok serialization.
    /// </summary>
    public static ApiEnvelopeContract<T> Success(T data, DateTimeOffset generatedAtUtc)
    {
        return new ApiEnvelopeContract<T>(true, data, null, generatedAtUtc);
    }

    /// <summary>
    /// Inputs: a structured error and a UTC timestamp from the caller.
    /// Processing: wraps the error with a failed envelope and clears the data field.
    /// Return behavior: returns an envelope suitable for non-2xx result serialization.
    /// </summary>
    public static ApiEnvelopeContract<T> Failure(ApiErrorContract error, DateTimeOffset generatedAtUtc)
    {
        return new ApiEnvelopeContract<T>(false, default, error, generatedAtUtc);
    }
}
